package kivimut;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class giris extends javax.swing.JFrame {

    /**
     * Creates new form giris
     */
    public giris() {
        initComponents();
        GirisYeniUcusBulButton.setVisible(false);
        GirisİleriButton.setVisible(false);
        Fiyat1TextField.setVisible(false);
        Fiyat2TextField.setVisible(false);
        Fiyat3TextField.setVisible(false);
        BosKoltuk1TextField.setVisible(false);
        BosKoltuk2TextField.setVisible(false);
        BosKoltuk3TextField.setVisible(false);
        jLabel6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        KalkisComboBox = new javax.swing.JComboBox();
        VarisComboBox = new javax.swing.JComboBox();
        TarihComboBox = new javax.swing.JComboBox();
        GirisUcusBulButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Saat1RadioButton = new javax.swing.JRadioButton();
        Saat2RadioButton = new javax.swing.JRadioButton();
        Saat3RadioButton = new javax.swing.JRadioButton();
        GirisYeniUcusBulButton = new javax.swing.JButton();
        GirisİleriButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Fiyat1TextField = new javax.swing.JTextField();
        Fiyat2TextField = new javax.swing.JTextField();
        Fiyat3TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BosKoltuk1TextField = new javax.swing.JTextField();
        BosKoltuk2TextField = new javax.swing.JTextField();
        BosKoltuk3TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        KalkisComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Izmir", "Istanbul", "Ankara" }));
        KalkisComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KalkisComboBoxActionPerformed(evt);
            }
        });

        TarihComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pazartesi", "Sali", "Carsamba", "Persembe", "Cuma", "Cumartesi", "Pazar" }));
        TarihComboBox.setToolTipText("");

        GirisUcusBulButton.setText("Ucus Bul");
        GirisUcusBulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirisUcusBulButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("NEREDEN:");

        jLabel2.setText("NEREYE:");

        jLabel3.setText("ZAMAN");

        Saat1RadioButton.setEnabled(false);
        Saat1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Saat1RadioButtonActionPerformed(evt);
            }
        });

        Saat2RadioButton.setEnabled(false);
        Saat2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Saat2RadioButtonActionPerformed(evt);
            }
        });

        Saat3RadioButton.setEnabled(false);
        Saat3RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Saat3RadioButtonActionPerformed(evt);
            }
        });

        GirisYeniUcusBulButton.setText("Yeni Uçuş BUL");
        GirisYeniUcusBulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirisYeniUcusBulButtonActionPerformed(evt);
            }
        });

        GirisİleriButton.setText("İLERLE");
        GirisİleriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirisİleriButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("FİYAT:");

        Fiyat1TextField.setEditable(false);
        Fiyat1TextField.setText("j");

        Fiyat2TextField.setEditable(false);
        Fiyat2TextField.setText("j");

        Fiyat3TextField.setEditable(false);
        Fiyat3TextField.setText("j");

        jLabel5.setText("BOŞ KOLTUK:");

        BosKoltuk1TextField.setEditable(false);
        BosKoltuk1TextField.setText("j");

        BosKoltuk2TextField.setEditable(false);
        BosKoltuk2TextField.setText("j");
        BosKoltuk2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BosKoltuk2TextFieldActionPerformed(evt);
            }
        });

        BosKoltuk3TextField.setEditable(false);
        BosKoltuk3TextField.setText("j");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("UCUS BULUNAMADI LÜTFEN YENİ BİR UÇUŞ BULUNUZ ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Fiyat1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Fiyat2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(Fiyat3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BosKoltuk2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(BosKoltuk3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(BosKoltuk1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GirisİleriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KalkisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Saat1RadioButton))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(Saat3RadioButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(Saat2RadioButton))
                                .addGap(12, 12, 12)
                                .addComponent(VarisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel3)
                                .addGap(43, 43, 43)
                                .addComponent(TarihComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GirisUcusBulButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GirisYeniUcusBulButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(VarisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(KalkisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TarihComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Saat1RadioButton)
                                    .addComponent(Saat3RadioButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(Saat2RadioButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(Fiyat2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fiyat3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fiyat1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(BosKoltuk2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BosKoltuk3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BosKoltuk1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GirisİleriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GirisUcusBulButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(GirisYeniUcusBulButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KalkisComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KalkisComboBoxActionPerformed
        // TODO add your handling code here:
        VarisComboBox.removeAllItems();
        if (KalkisComboBox.getSelectedItem() == "Izmir") {
            VarisComboBox.addItem("Ankara");
            VarisComboBox.addItem("Istanbul");
        } else if (KalkisComboBox.getSelectedItem() == "Istanbul") {
            VarisComboBox.addItem("Ankara");
            VarisComboBox.addItem("Izmir");
        } else if (KalkisComboBox.getSelectedItem() == "Ankara") {
            VarisComboBox.addItem("Istanbul");
            VarisComboBox.addItem("Izmir");
        }
    }//GEN-LAST:event_KalkisComboBoxActionPerformed

    private void GirisUcusBulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirisUcusBulButtonActionPerformed
        // TODO add your handling code here:
        Dosya d = new Dosya();
        try {
            String[] veriler = d.DosyaOku();
            for (int i = 0; i < 15; i++) {
                String[] veri = veriler[i].split(";");
                String debug = (String) TarihComboBox.getSelectedItem();
                String debug2 = (String) KalkisComboBox.getSelectedItem();
                String debug3 = (String) VarisComboBox.getSelectedItem();
                if (veri[0].equals(debug) && veri[1].equals(debug2) && veri[2].equals(debug3)) {
                    if (Saat1RadioButton.getText() == "" && Integer.parseInt(veri[5]) > 0) {
                        Saat1RadioButton.setText(veri[3]);
                        Saat1RadioButton.setEnabled(true);
                        Fiyat1TextField.setText(veri[4]);
                        BosKoltuk1TextField.setText(veri[5]);
                        continue;
                    }
                    if (Saat2RadioButton.getText() == "" && Integer.parseInt(veri[5]) > 0) {
                        Saat2RadioButton.setText(veri[3]);
                        Saat2RadioButton.setEnabled(true);
                        Fiyat2TextField.setText(veri[4]);
                        BosKoltuk2TextField.setText(veri[5]);
                        continue;
                    }
                    if (Saat3RadioButton.getText() == "" && Integer.parseInt(veri[5]) > 0) {
                        Saat3RadioButton.setText(veri[3]);
                        Saat3RadioButton.setEnabled(true);
                        Fiyat3TextField.setText(veri[4]);
                        BosKoltuk3TextField.setText(veri[5]);
                        continue;
                    } 
                    else{
                        jLabel6.setVisible(true);
                        GirisİleriButton.setVisible(false);
                    }
                }

            }
        } catch (IOException ex) {
            Logger.getLogger(giris.class.getName()).log(Level.SEVERE, null, ex);
        }
        GirisUcusBulButton.setVisible(false);
        GirisYeniUcusBulButton.setVisible(true);
        GirisİleriButton.setVisible(true);
    }//GEN-LAST:event_GirisUcusBulButtonActionPerformed

    private void GirisYeniUcusBulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirisYeniUcusBulButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new giris().setVisible(true);
    }//GEN-LAST:event_GirisYeniUcusBulButtonActionPerformed

    private void BosKoltuk2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BosKoltuk2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BosKoltuk2TextFieldActionPerformed

    private void GirisİleriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirisİleriButtonActionPerformed
        // TODO add your handling code here:

        Bilet b = new Bilet();
        b.setVisible(true);
        new giris().setVisible(false);
    }//GEN-LAST:event_GirisİleriButtonActionPerformed

    private void Saat1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Saat1RadioButtonActionPerformed
        // TODO add your handling code here:
        Fiyat1TextField.setVisible(true);
        BosKoltuk1TextField.setVisible(true);
    }//GEN-LAST:event_Saat1RadioButtonActionPerformed

    private void Saat2RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Saat2RadioButtonActionPerformed
        // TODO add your handling code here:
        Fiyat2TextField.setVisible(true);
        BosKoltuk2TextField.setVisible(true);
    }//GEN-LAST:event_Saat2RadioButtonActionPerformed

    private void Saat3RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Saat3RadioButtonActionPerformed
        // TODO add your handling code here:
        Fiyat3TextField.setVisible(true);
        BosKoltuk3TextField.setVisible(true);
    }//GEN-LAST:event_Saat3RadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giris().setVisible(true);
            }
        });
    }

    private void readData() {
        //reads data from file and adds the items to the jTable

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BosKoltuk1TextField;
    private javax.swing.JTextField BosKoltuk2TextField;
    private javax.swing.JTextField BosKoltuk3TextField;
    private javax.swing.JTextField Fiyat1TextField;
    private javax.swing.JTextField Fiyat2TextField;
    private javax.swing.JTextField Fiyat3TextField;
    private javax.swing.JButton GirisUcusBulButton;
    private javax.swing.JButton GirisYeniUcusBulButton;
    private javax.swing.JButton GirisİleriButton;
    private javax.swing.JComboBox KalkisComboBox;
    private javax.swing.JRadioButton Saat1RadioButton;
    private javax.swing.JRadioButton Saat2RadioButton;
    private javax.swing.JRadioButton Saat3RadioButton;
    private javax.swing.JComboBox TarihComboBox;
    private javax.swing.JComboBox VarisComboBox;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
