
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kivancenes
 */
public class MainScreen extends javax.swing.JFrame {

    public static int speed;
    public static int distance;
    public static Integer mspeedinput;
    public static String speed1;
    public static String speed2;
    public static String speed3;
    public static String speed4;
    public static String distance1;
    public static String distance2;
    public static String distance3;
    public static String distance4;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Speed_ComboBox = new javax.swing.JComboBox();
        Distance_ComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Speed_ComboBox2 = new javax.swing.JComboBox();
        Speed_ComboBox3 = new javax.swing.JComboBox();
        Distance_ComboBox2 = new javax.swing.JComboBox();
        Distance_ComboBox3 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MotorSpeedInput_ComboBox = new javax.swing.JComboBox();
        MotorSpeed_TextField1 = new javax.swing.JTextField();
        MotorSpeed_TextField2 = new javax.swing.JTextField();
        Speed_Button = new javax.swing.JButton();
        Distance_Button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MotorSpeed_Button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Analysis_Button = new javax.swing.JButton();
        Distance_ComboBox4 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        MotorSpeed_TextField3 = new javax.swing.JTextField();
        MotorSpeed_TextField4 = new javax.swing.JTextField();
        Speed_ComboBox4 = new javax.swing.JComboBox();
        Speed_ComboBox5 = new javax.swing.JComboBox();
        Distance_ComboBox5 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Speed_ComboBox.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        Speed_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200" }));
        Speed_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Speed_ComboBoxActionPerformed(evt);
            }
        });

        Distance_ComboBox.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        Distance_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setText("Speed");

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setText("Distance");

        Speed_ComboBox2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Speed_ComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Very Slow", "Slow", "Medium", "Fast", "Very Fast" }));
        Speed_ComboBox2.setSelectedIndex(-1);
        Speed_ComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Speed_ComboBox2ActionPerformed(evt);
            }
        });

        Speed_ComboBox3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Speed_ComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Very Slow", "Slow", "Medium", "Fast", "Very Fast" }));
        Speed_ComboBox3.setSelectedIndex(-1);
        Speed_ComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Speed_ComboBox3ActionPerformed(evt);
            }
        });

        Distance_ComboBox2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        Distance_ComboBox3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel3.setText("AND");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel4.setText("AND");

        MotorSpeedInput_ComboBox.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        MotorSpeedInput_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        MotorSpeed_TextField1.setEditable(false);
        MotorSpeed_TextField1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        MotorSpeed_TextField1.setText("STOP");
        MotorSpeed_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotorSpeed_TextField1ActionPerformed(evt);
            }
        });

        MotorSpeed_TextField2.setEditable(false);
        MotorSpeed_TextField2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        MotorSpeed_TextField2.setText("SLOW DOWN");
        MotorSpeed_TextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotorSpeed_TextField2ActionPerformed(evt);
            }
        });

        Speed_Button.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Speed_Button.setText("Speed Graphs");
        Speed_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Speed_ButtonActionPerformed(evt);
            }
        });

        Distance_Button.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Distance_Button.setText("Distance Graphs");
        Distance_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Distance_ButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel5.setText("THEN");

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel6.setText("THEN");

        MotorSpeed_Button.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        MotorSpeed_Button.setText("Motor Speed Graphs");
        MotorSpeed_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotorSpeed_ButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel7.setText("Motor Speed");

        Analysis_Button.setText("Analysis");
        Analysis_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Analysis_ButtonActionPerformed(evt);
            }
        });

        Distance_ComboBox4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel8.setText("AND");

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel9.setText("AND");

        MotorSpeed_TextField3.setEditable(false);
        MotorSpeed_TextField3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        MotorSpeed_TextField3.setText("KEEP PACE");
        MotorSpeed_TextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotorSpeed_TextField3ActionPerformed(evt);
            }
        });

        MotorSpeed_TextField4.setEditable(false);
        MotorSpeed_TextField4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        MotorSpeed_TextField4.setText("SPEED UP");

        Speed_ComboBox4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Speed_ComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Very Slow", "Slow", "Medium", "Fast", "Very Fast" }));
        Speed_ComboBox4.setSelectedIndex(-1);
        Speed_ComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Speed_ComboBox4ActionPerformed(evt);
            }
        });

        Speed_ComboBox5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Speed_ComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Very Slow", "Slow", "Medium", "Fast", "Very Fast" }));
        Speed_ComboBox5.setSelectedIndex(-1);
        Speed_ComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Speed_ComboBox5ActionPerformed(evt);
            }
        });

        Distance_ComboBox5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel10.setText("THEN");

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel11.setText("THEN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(181, 181, 181)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Speed_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(Distance_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247)
                        .addComponent(MotorSpeedInput_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Speed_ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)
                        .addComponent(Distance_ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40)
                        .addComponent(MotorSpeed_TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Speed_ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Speed_ComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Distance_ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Distance_ComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MotorSpeed_TextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(MotorSpeed_TextField2))
                        .addGap(83, 83, 83)
                        .addComponent(Analysis_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Speed_ComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel9)
                        .addGap(40, 40, 40)
                        .addComponent(Distance_ComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel11)
                        .addGap(40, 40, 40)
                        .addComponent(MotorSpeed_TextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Speed_Button)
                        .addGap(111, 111, 111)
                        .addComponent(Distance_Button)
                        .addGap(177, 177, 177)
                        .addComponent(MotorSpeed_Button))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Speed_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Distance_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MotorSpeedInput_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Speed_ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Distance_ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MotorSpeed_TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Speed_ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(Speed_ComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Distance_ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(Distance_ComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(MotorSpeed_TextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Analysis_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MotorSpeed_TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(Speed_ComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(Distance_ComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(MotorSpeed_TextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MotorSpeed_Button)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Speed_Button)
                            .addComponent(Distance_Button)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Speed_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Speed_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Speed_ComboBoxActionPerformed

    private void Speed_ComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Speed_ComboBox2ActionPerformed
        // TODO add your handling code here:
        Distance_ComboBox2.removeAllItems();
        if (Speed_ComboBox2.getSelectedItem().equals("Slow") || Speed_ComboBox2.getSelectedItem().equals("Medium")
                || Speed_ComboBox2.getSelectedItem().equals("Fast") || Speed_ComboBox2.getSelectedItem().equals("Very Fast")) {
            Distance_ComboBox2.removeAllItems();
            Distance_ComboBox2.addItem("Very Close");
        }
    }//GEN-LAST:event_Speed_ComboBox2ActionPerformed

    private void MotorSpeed_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorSpeed_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotorSpeed_TextField1ActionPerformed

    private void MotorSpeed_TextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorSpeed_TextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotorSpeed_TextField2ActionPerformed

    private void Speed_ComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Speed_ComboBox3ActionPerformed
        // TODO add your handling code here:
        Distance_ComboBox3.removeAllItems();
        if (Speed_ComboBox3.getSelectedItem().equals("Slow") || Speed_ComboBox3.getSelectedItem().equals("Medium")
                || Speed_ComboBox3.getSelectedItem().equals("Fast") || Speed_ComboBox3.getSelectedItem().equals("Very Fast")) {
            Distance_ComboBox3.removeAllItems();
            Distance_ComboBox3.addItem("Close");
        }
        if (Speed_ComboBox3.getSelectedItem().equals("Very Fast")) {
            Distance_ComboBox3.removeAllItems();
            Distance_ComboBox3.addItem("Normal");
            Distance_ComboBox3.addItem("Close");
        }

    }//GEN-LAST:event_Speed_ComboBox3ActionPerformed

    private void Speed_ComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Speed_ComboBox4ActionPerformed
        // TODO add your handling code here:
        Distance_ComboBox4.removeAllItems();
        if (Speed_ComboBox4.getSelectedItem().equals("Fast")) {
            Distance_ComboBox4.removeAllItems();
            Distance_ComboBox4.addItem("Normal");
        }
        if (Speed_ComboBox4.getSelectedItem().equals("Very Slow")) {
            Distance_ComboBox4.removeAllItems();
            Distance_ComboBox4.addItem("Close");
            Distance_ComboBox4.addItem("Very Close");
        }
    }//GEN-LAST:event_Speed_ComboBox4ActionPerformed

    private void Speed_ComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Speed_ComboBox5ActionPerformed
        // TODO add your handling code here:
        Distance_ComboBox5.removeAllItems();
        if (Speed_ComboBox5.getSelectedItem().equals("Slow") || Speed_ComboBox5.getSelectedItem().equals("Very Slow")
                || Speed_ComboBox5.getSelectedItem().equals("Fast") || Speed_ComboBox5.getSelectedItem().equals("Very Fast")) {
            Distance_ComboBox5.removeAllItems();
            Distance_ComboBox5.addItem("Normal");
            Distance_ComboBox5.addItem("Away");
        }
    }//GEN-LAST:event_Speed_ComboBox5ActionPerformed

    private void Speed_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Speed_ButtonActionPerformed
        // TODO add your handling code here:
        XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries VerySlow = new XYSeries("Very Slow");
        XYSeries Slow = new XYSeries("Slow");
        XYSeries Medium = new XYSeries("Medium");
        XYSeries Fast = new XYSeries("Fast");
        XYSeries VeryFast = new XYSeries("Very Fast");

        VerySlow.add(0, 1);//x i 0 ken y si 1
        VerySlow.add(40, 1);//x i 40 ken y si 1
        VerySlow.add(70, 0);//x i 70 ken y si 0       
        dataset.addSeries(VerySlow);

        Slow.add(40, 0);//x i 40 ken y si 0
        Slow.add(70, 1);//x i 70 ken y si 1
        Slow.add(90, 0);//x i 90 ken y si 0       
        dataset.addSeries(Slow);

        Medium.add(50, 0);//x i 50 ken y si 0
        Medium.add(100, 1);//x i 100 ken y si 1
        Medium.add(130, 0);//x i 130 ken y si 0       
        dataset.addSeries(Medium);

        Fast.add(110, 0);//x i 110 ken y si 0
        Fast.add(140, 1);//x i 140 ken y si 1
        Fast.add(170, 0);//x i 170 ken y si 0       
        dataset.addSeries(Fast);

        VeryFast.add(120, 0);//x i 120 ken y si 0
        VeryFast.add(160, 1);//x i 160 ken y si 1
        VeryFast.add(200, 1);//x i 200 ken y si 0       
        dataset.addSeries(VeryFast);

        JFreeChart chart = ChartFactory.createXYLineChart("Speed Graph", "Speed", "Membership", dataset);
        ChartFrame frame = new ChartFrame("Speed Graph", chart);
        frame.setVisible(true);
        frame.setSize(500, 300);


    }//GEN-LAST:event_Speed_ButtonActionPerformed

    private void Distance_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Distance_ButtonActionPerformed
        // TODO add your handling code here:
        XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries VeryClose = new XYSeries("Very Close");
        XYSeries Close = new XYSeries("Close");
        XYSeries Normal = new XYSeries("Normal");
        XYSeries Away = new XYSeries("Away");

        VeryClose.add(0, 1);//x i 0 ken y si 1
        VeryClose.add(20, 1);//x i 20 ken y si 1
        VeryClose.add(40, 0);//x i 40 ken y si 0       
        dataset.addSeries(VeryClose);

        Close.add(20, 0);//x i 20 ken y si 0
        Close.add(40, 1);//x i 40 ken y si 1
        Close.add(60, 0);//x i 60 ken y si 0       
        dataset.addSeries(Close);

        Normal.add(40, 0);//x i 40 ken y si 0
        Normal.add(60, 1);//x i 60 ken y si 1
        Normal.add(80, 0);//x i 80 ken y si 0       
        dataset.addSeries(Normal);

        Away.add(60, 0);//x i 60 ken y si 0
        Away.add(80, 1);//x i 80 ken y si 1
        Away.add(100, 1);//x i 100 ken y si 1s       
        dataset.addSeries(Away);

        JFreeChart chart = ChartFactory.createXYLineChart("Distance Graph", "Distance", "Membership", dataset);
        ChartFrame frame = new ChartFrame("Distance Graph", chart);
        frame.setVisible(true);
        frame.setSize(500, 300);
    }//GEN-LAST:event_Distance_ButtonActionPerformed

    private void MotorSpeed_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorSpeed_ButtonActionPerformed
        // TODO add your handling code here:
        XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries Stop = new XYSeries("Stop");
        XYSeries SlowDown = new XYSeries("SlowDown");
        XYSeries KeepPace = new XYSeries("KeepPace");
        XYSeries SpeedUp = new XYSeries("SpeedUp");

        Stop.add(0, 1);//x i 0 ken y si 1
        Stop.add(2, 1);//x i 2 ken y si 1
        Stop.add(4, 0);//x i 4 ken y si 0       
        dataset.addSeries(Stop);

        SlowDown.add(2, 0);//x i 2 ken y si 0
        SlowDown.add(4, 1);//x i 4 ken y si 1
        SlowDown.add(6, 0);//x i 6 ken y si 0       
        dataset.addSeries(SlowDown);

        KeepPace.add(4, 0);//x i 4 ken y si 0
        KeepPace.add(6, 1);//x i 6 ken y si 1
        KeepPace.add(8, 0);//x i 8 ken y si 0       
        dataset.addSeries(KeepPace);

        SpeedUp.add(6, 0);//x i 6 ken y si 0
        SpeedUp.add(8, 1);//x i 8 ken y si 1
        SpeedUp.add(10, 1);//x i 10 ken y si 1s       
        dataset.addSeries(SpeedUp);

        JFreeChart chart = ChartFactory.createXYLineChart("Motor Speed Graph", "Motor Speed", "Membership", dataset);
        ChartFrame frame = new ChartFrame("Motor Speed Graph", chart);
        frame.setVisible(true);
        frame.setSize(500, 300);
    }//GEN-LAST:event_MotorSpeed_ButtonActionPerformed

    private void Analysis_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Analysis_ButtonActionPerformed
        // TODO add your handling code here:

        try {
            speed = Integer.parseInt(Speed_ComboBox.getSelectedItem().toString());
            speed1 = Speed_ComboBox2.getSelectedItem().toString();
            speed2 = Speed_ComboBox3.getSelectedItem().toString();
            speed3 = Speed_ComboBox4.getSelectedItem().toString();
            speed4 = Speed_ComboBox5.getSelectedItem().toString();
            distance = Integer.parseInt(Distance_ComboBox.getSelectedItem().toString());
            distance1 = Distance_ComboBox2.getSelectedItem().toString();
            distance2 = Distance_ComboBox3.getSelectedItem().toString();
            distance3 = Distance_ComboBox4.getSelectedItem().toString();
            distance4 = Distance_ComboBox5.getSelectedItem().toString();
            mspeedinput = Integer.parseInt(MotorSpeedInput_ComboBox.getSelectedItem().toString());
            SecondScreen frame = new SecondScreen();
            frame.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Select All Rules");
        }


    }//GEN-LAST:event_Analysis_ButtonActionPerformed

    private void MotorSpeed_TextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorSpeed_TextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotorSpeed_TextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Analysis_Button;
    private javax.swing.JButton Distance_Button;
    private javax.swing.JComboBox Distance_ComboBox;
    private javax.swing.JComboBox Distance_ComboBox2;
    private javax.swing.JComboBox Distance_ComboBox3;
    private javax.swing.JComboBox Distance_ComboBox4;
    private javax.swing.JComboBox Distance_ComboBox5;
    private javax.swing.JComboBox MotorSpeedInput_ComboBox;
    private javax.swing.JButton MotorSpeed_Button;
    private javax.swing.JTextField MotorSpeed_TextField1;
    private javax.swing.JTextField MotorSpeed_TextField2;
    private javax.swing.JTextField MotorSpeed_TextField3;
    private javax.swing.JTextField MotorSpeed_TextField4;
    private javax.swing.JButton Speed_Button;
    private javax.swing.JComboBox Speed_ComboBox;
    private javax.swing.JComboBox Speed_ComboBox2;
    private javax.swing.JComboBox Speed_ComboBox3;
    private javax.swing.JComboBox Speed_ComboBox4;
    private javax.swing.JComboBox Speed_ComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
