
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kivancenes
 */
public class ThirdScreen extends javax.swing.JFrame {

    /**
     * Creates new form ThirdScreen
     */
    public ThirdScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Defuzzification_Button = new javax.swing.JButton();
        Aggregation_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Defuzzification_Button.setText("Defuzzification");
        Defuzzification_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Defuzzification_ButtonActionPerformed(evt);
            }
        });

        Aggregation_Button.setText("Aggregation");
        Aggregation_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aggregation_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Select:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Aggregation_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Defuzzification_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aggregation_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Defuzzification_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Defuzzification_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Defuzzification_ButtonActionPerformed
        // TODO add your handling code here:

        //weighted average yöntemini kullanarak defuzzification yapıyoruz.
        //0-1-2 arası stop baskın o yüzden 1+2=3
        //3-4-5
        //6-7-8
        //9-10
        Double WeAve = (3 * SecondScreen.FirstRuleMembership + 12 * SecondScreen.SecondRuleMembership + 21 * SecondScreen.ThirdRuleMembership + 19 * SecondScreen.FourthRuleMembership)
                / (SecondScreen.FirstRuleMembership * 2 + SecondScreen.SecondRuleMembership * 3 + SecondScreen.ThirdRuleMembership * 3 + SecondScreen.FourthRuleMembership * 2);
        String Deffz = "";
        String WeightedAve = WeAve.toString();
        if (WeAve >= 0.0 && WeAve <= 2.0) {
            Deffz = "Stop";
        } else if (WeAve > 2.0 && WeAve <= 5.0) {
            Deffz = "Slow Down";
        } else if (WeAve > 5.0 && WeAve <= 8.0) {
            Deffz = "Keep Pace";
        } else if (WeAve > 8.0 && WeAve <= 10.0) {
            Deffz = "Speed Up";
        } else {
            WeightedAve = "0.0";
            Deffz = "Stop";
        }
        String MotSpeedIn = MainScreen.mspeedinput.toString();
        JOptionPane.showMessageDialog(this, "Defuzzified Output = " + Deffz + "\nOur fuzzy system recommends that the motor speed should be quantified as " + WeightedAve + " \nYou guessed :  " + MotSpeedIn, "Defuzzification", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_Defuzzification_ButtonActionPerformed

    private void Aggregation_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aggregation_ButtonActionPerformed
        XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries Aggregation = new XYSeries("Aggregation", false);

        Aggregation.add(0, SecondScreen.FirstRuleMembership);
        Aggregation.add(((1 - SecondScreen.FirstRuleMembership) * 2 + 2), SecondScreen.FirstRuleMembership);//x 'i inme kuralı y side y.
        Aggregation.add(4, 0);
        Aggregation.add(2, 0);
        Aggregation.add((SecondScreen.SecondRuleMembership * 2 + 2), SecondScreen.SecondRuleMembership);
        Aggregation.add(((1 - SecondScreen.SecondRuleMembership) * 2) + 4, SecondScreen.SecondRuleMembership);
        Aggregation.add(6, 0);
        Aggregation.add(4, 0);
        Aggregation.add((SecondScreen.ThirdRuleMembership * 2 + 4), SecondScreen.ThirdRuleMembership);
        Aggregation.add(((1 - SecondScreen.ThirdRuleMembership) * 2) + 6, SecondScreen.ThirdRuleMembership);
        Aggregation.add(8, 0);
        Aggregation.add(6, 0);
        Aggregation.add((SecondScreen.FourthRuleMembership * 2 + 6), SecondScreen.FourthRuleMembership);
        Aggregation.add(10, SecondScreen.FourthRuleMembership);

        dataset.addSeries(Aggregation);

        JFreeChart chart = ChartFactory.createXYLineChart("Aggregation Graph", "Motor Speed", "Membership", dataset);
        ChartFrame frame = new ChartFrame("Aggregation", chart);
        frame.setVisible(true);
        frame.setSize(500, 300);
    }//GEN-LAST:event_Aggregation_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThirdScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThirdScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThirdScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThirdScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThirdScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aggregation_Button;
    private javax.swing.JButton Defuzzification_Button;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
